from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field

class ServiceCosts(BaseModel):
    fixed_costs: float = Field(..., description="Operational overhead costs")
    variable_costs: float = Field(..., description="Contractor payments, resource consumption")
    
class ServiceMetrics(BaseModel):
    revenue: float = Field(..., description="Revenue generated by service")
    usage_count: int = Field(..., description="Number of times service was used")
    profit_margin: float = Field(..., description="Calculated profit margin percentage")
    
class ServiceResources(BaseModel):
    equipment_required: List[str] = Field(default_factory=list, description="Required equipment")
    contractor_count: int = Field(..., description="Number of contractors needed")
    
class ServicePerformance(BaseModel):
    monthly_profits: List[float] = Field(..., description="Last 12 months of profit data")
    seasonal_trends: dict = Field(..., description="Seasonal performance patterns")
    
class Service(BaseModel):
    id: str = Field(..., description="Unique service identifier")
    name: str = Field(..., description="Service name")
    description: str = Field(..., description="Service description")
    category: str = Field(..., description="Current classification (Profitable/Optimization/Unprofitable)")
    costs: ServiceCosts
    metrics: ServiceMetrics
    resources: ServiceResources
    performance: ServicePerformance
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    
class ServiceClassification(BaseModel):
    service_id: str
    category: str
    confidence_score: float = Field(..., description="ML model confidence in classification")
    optimization_suggestions: List[str] = Field(default_factory=list)
    market_insights: dict = Field(..., description="AI-gathered market research data")
